"""Holler CLI -- four commands to first call.

pip install holler -> holler init -> holler trunk add -> holler call
"""
import asyncio
import os
import subprocess
import sys
import time
from pathlib import Path

import click
import structlog

logger = structlog.get_logger()


def _get_project_root() -> Path:
    """Locate the project root (parent of holler/ package).

    Navigates: commands.py -> cli/ -> holler/ -> project_root/
    Works regardless of the user's current working directory.
    """
    return Path(__file__).resolve().parent.parent.parent


@click.group()
@click.version_option(package_name="holler")
def cli():
    """Holler -- voice and text infrastructure for AI agents.

    You don't need permission to holler.
    """
    pass


@cli.command()
def init():
    """Download models and start local services.

    Downloads faster-whisper and Kokoro ONNX models, generates .holler.env
    config with defaults, and starts FreeSWITCH + Redis via Docker Compose.
    """
    click.echo("Holler init -- setting up local infrastructure")
    click.echo()

    # 1. Check GPU availability
    _check_gpu()

    # 2. Download models
    _download_models()

    # 3. Generate .holler.env if it doesn't exist
    _generate_env_file()

    # 4. Start Docker Compose services
    _start_services()

    click.echo()
    click.secho("Holler initialized.", fg="green", bold=True)
    click.echo("Next: holler trunk add")


@cli.command("trunk")
@click.option("--host", prompt="SIP trunk host", help="SIP trunk hostname or IP")
@click.option("--user", prompt="Username", help="SIP authentication username")
@click.option(
    "--password",
    "--pass",
    prompt="Password",
    hide_input=True,
    help="SIP authentication password (alias: --pass, per D-15)",
)
def trunk_add(host, user, password):
    """Configure SIP trunk credentials.

    Writes trunk config to .holler.env. Use --host, --user, --pass
    flags for non-interactive mode.
    """
    _write_trunk_config(host, user, password)
    click.secho(f"Trunk configured: {user}@{host}", fg="green")
    click.echo("Next: holler call +1XXXXXXXXXX")


@cli.command("call")
@click.argument("destination")
@click.option("--agent", default=None, help="System prompt for the call agent")
def call(destination, agent):
    """Place a call to DESTINATION (E.164 format, e.g. +14155551234).

    Uses a default voice assistant prompt. Override with --agent "your prompt".
    """
    structlog.configure(
        processors=[
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.add_log_level,
            structlog.dev.ConsoleRenderer(),
        ],
    )
    click.echo(f"Calling {destination}...")
    from holler.main import main
    asyncio.run(main(call_destination=destination, agent_prompt=agent))


# --- Helper functions ---

def _check_gpu():
    """Check for GPU availability and report."""
    try:
        import torch
        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            click.echo(f"  GPU detected: {gpu_name}")
        else:
            click.echo("  No GPU detected -- using CPU (slower, limited concurrent calls)")
    except ImportError:
        click.echo("  No GPU detected -- using CPU (slower, limited concurrent calls)")


def _download_models():
    """Download faster-whisper and Kokoro ONNX models."""
    click.echo("  Downloading models...")

    # faster-whisper model (uses huggingface_hub internally)
    try:
        click.echo("    faster-whisper distil-large-v3...", nl=False)
        from faster_whisper import WhisperModel
        WhisperModel("distil-large-v3", device="cpu", compute_type="int8")
        click.secho(" done", fg="green")
    except Exception as e:
        click.secho(f" failed: {e}", fg="red")

    # Kokoro ONNX model
    try:
        click.echo("    Kokoro ONNX model...", nl=False)
        from huggingface_hub import hf_hub_download
        hf_hub_download("fastrtc/kokoro-onnx", "kokoro-v1.0.onnx")
        hf_hub_download("fastrtc/kokoro-onnx", "voices-v1.0.bin")
        click.secho(" done", fg="green")
    except Exception as e:
        click.secho(f" failed: {e}", fg="red")


def _generate_env_file():
    """Generate .holler.env with sensible defaults if it doesn't exist."""
    env_path = ".holler.env"
    if os.path.exists(env_path):
        click.echo(f"  Config file {env_path} already exists -- skipping")
        return

    defaults = [
        "# Holler configuration",
        "# Generated by holler init",
        "",
        "# FreeSWITCH ESL",
        "ESL_HOST=127.0.0.1",
        "ESL_PORT=8021",
        "ESL_PASSWORD=ClueCon",
        "",
        "# Voice pipeline",
        "WHISPER_MODEL=distil-large-v3",
        "WHISPER_DEVICE=cpu",
        "WHISPER_COMPUTE_TYPE=int8",
        "KOKORO_VOICE=af_sarah",
        "",
        "# LLM",
        "LLM_BASE_URL=http://localhost:11434/v1",
        "LLM_API_KEY=ollama",
        "LLM_MODEL=llama3.2",
        "",
        "# Redis",
        "HOLLER_REDIS_URL=redis://localhost:6379",
        "",
        "# Number pool (comma-separated E.164 DIDs)",
        "HOLLER_POOL_DIDS=",
        "",
        "# SIP trunk (set via 'holler trunk add')",
        "HOLLER_TRUNK_HOST=",
        "HOLLER_TRUNK_USER=",
        "HOLLER_TRUNK_PASS=",
        "",
        "# SMPP (optional SMS gateway)",
        "HOLLER_SMSC_HOST=127.0.0.1",
        "HOLLER_SMSC_PORT=2775",
        "HOLLER_SMSC_SYSTEM_ID=holler",
        "HOLLER_SMSC_PASSWORD=",
        "HOLLER_SMS_SOURCE=",
        "",
    ]
    with open(env_path, "w") as f:
        f.write("\n".join(defaults) + "\n")
    click.echo(f"  Generated {env_path}")


def _write_trunk_config(host, user, password):
    """Write SIP trunk credentials to .holler.env."""
    env_path = ".holler.env"
    lines = []
    if os.path.exists(env_path):
        with open(env_path) as f:
            lines = f.readlines()

    # Update or append trunk config
    trunk_vars = {
        "HOLLER_TRUNK_HOST": host,
        "HOLLER_TRUNK_USER": user,
        "HOLLER_TRUNK_PASS": password,
    }
    updated_keys = set()
    new_lines = []
    for line in lines:
        key = line.split("=", 1)[0].strip()
        if key in trunk_vars:
            new_lines.append(f"{key}={trunk_vars[key]}\n")
            updated_keys.add(key)
        else:
            new_lines.append(line)

    # Append any keys not found in existing file
    for key, value in trunk_vars.items():
        if key not in updated_keys:
            new_lines.append(f"{key}={value}\n")

    with open(env_path, "w") as f:
        f.writelines(new_lines)


def _start_services():
    """Start Docker Compose services and wait for health."""
    click.echo("  Starting Docker Compose services...")

    # Check HOLLER_COMPOSE_FILE env var as an explicit override first
    env_compose = os.environ.get("HOLLER_COMPOSE_FILE")
    if env_compose:
        compose_file = Path(env_compose)
        if not compose_file.exists():
            click.secho(f"  HOLLER_COMPOSE_FILE={env_compose} not found", fg="red")
            return
    else:
        # Primary: resolve from package location (works in source checkout / editable install)
        project_root = _get_project_root()
        compose_file = project_root / "docker" / "docker-compose.yml"

        # Fallback: check CWD (works when user is in project dir with pip install)
        if not compose_file.exists():
            compose_file = Path.cwd() / "docker" / "docker-compose.yml"

        if not compose_file.exists():
            click.secho(
                "  docker-compose.yml not found. Run from the holler project directory,\n"
                "  or set HOLLER_COMPOSE_FILE to the path of your docker-compose.yml.",
                fg="red",
            )
            return

    try:
        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_file),
             "--project-directory", str(compose_file.parent),
             "up", "-d"],
            capture_output=True, text=True, timeout=120
        )
        if result.returncode != 0:
            click.secho(f"  Docker Compose failed: {result.stderr}", fg="red")
            return

        # Wait for FreeSWITCH ESL port to be ready
        click.echo("  Waiting for FreeSWITCH...", nl=False)
        import socket
        for _ in range(30):  # 30 second timeout
            try:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(1)
                sock.connect(("127.0.0.1", 8021))
                sock.close()
                click.secho(" ready", fg="green")
                return
            except (ConnectionRefusedError, socket.timeout, OSError):
                time.sleep(1)
        click.secho(" timeout (FreeSWITCH not responding on port 8021)", fg="yellow")
    except FileNotFoundError:
        click.secho("  Docker not found -- install Docker and try again", fg="red")
    except subprocess.TimeoutExpired:
        click.secho("  Docker Compose timed out", fg="red")
