"""US area code (NPA) to IANA timezone mapping.

Static dictionary covering all active NANPA US NPAs (~380 entries).
Used by the US compliance module for TCPA time-of-day enforcement (D-11, D-13).

If the destination NPA is not in this map, the call is DENIED (fail-closed per D-13).

Source: NANPA NPA list — https://www.nanpa.com/area_codes/view_npa_reports.html
Generated: 2026-03-24 (covers active US NPAs as of NANPA report)

Usage:
    from holler.countries.us.timezones import NPA_TIMEZONES, get_timezone_for_npa
    tz = get_timezone_for_npa("+12125551234")  # "America/New_York"
"""
from __future__ import annotations

from typing import Optional

# NPA (area code) -> IANA timezone string
# Covers all active US NPAs. Key: 3-digit string. Value: IANA tz name.
# Note: NPAs in border areas (e.g., some Indiana counties, parts of AZ) follow the
# dominant timezone for that NPA. This is a best-effort conservative mapping —
# unknown NPAs fail closed (per D-13).
NPA_TIMEZONES: dict[str, str] = {
    # ---- Eastern Time (America/New_York) ----
    "201": "America/New_York",  # NJ
    "202": "America/New_York",  # DC
    "203": "America/New_York",  # CT
    "207": "America/New_York",  # ME
    "212": "America/New_York",  # NY (Manhattan)
    "215": "America/New_York",  # PA (Philadelphia)
    "216": "America/New_York",  # OH (Cleveland)
    "218": "America/Chicago",   # MN (Duluth - Central)
    "220": "America/New_York",  # OH
    "224": "America/Chicago",   # IL (Chicago suburbs - Central)
    "225": "America/Chicago",   # LA (Baton Rouge - Central)
    "228": "America/Chicago",   # MS (Gulf Coast - Central)
    "229": "America/New_York",  # GA (Albany)
    "231": "America/New_York",  # MI (western)
    "234": "America/New_York",  # OH (Akron)
    "239": "America/New_York",  # FL (Naples/Fort Myers)
    "240": "America/New_York",  # MD
    "248": "America/New_York",  # MI (Oakland County)
    "251": "America/Chicago",   # AL (Mobile - Central)
    "252": "America/New_York",  # NC (eastern)
    "253": "America/Los_Angeles", # WA (Tacoma - Pacific)
    "256": "America/Chicago",   # AL (northern - Central)
    "260": "America/New_York",  # IN (Fort Wayne - Eastern observed)
    "267": "America/New_York",  # PA (Philadelphia overlay)
    "269": "America/New_York",  # MI (Kalamazoo)
    "270": "America/Chicago",   # KY (western - Central)
    "272": "America/New_York",  # PA (Scranton overlay)
    "276": "America/New_York",  # VA (western)
    "279": "America/Los_Angeles", # CA (Sacramento area - Pacific)
    "281": "America/Chicago",   # TX (Houston - Central)
    "301": "America/New_York",  # MD
    "302": "America/New_York",  # DE
    "303": "America/Denver",    # CO (Denver)
    "304": "America/New_York",  # WV
    "305": "America/New_York",  # FL (Miami)
    "307": "America/Denver",    # WY
    "308": "America/Chicago",   # NE (western - Central)
    "309": "America/Chicago",   # IL (Peoria - Central)
    "310": "America/Los_Angeles", # CA (LA west side)
    "312": "America/Chicago",   # IL (Chicago - Central)
    "313": "America/New_York",  # MI (Detroit)
    "314": "America/Chicago",   # MO (St. Louis - Central)
    "315": "America/New_York",  # NY (Syracuse)
    "316": "America/Chicago",   # KS (Wichita - Central)
    "317": "America/New_York",  # IN (Indianapolis - Eastern observed)
    "318": "America/Chicago",   # LA (Shreveport - Central)
    "319": "America/Chicago",   # IA (Cedar Rapids - Central)
    "320": "America/Chicago",   # MN (St. Cloud - Central)
    "321": "America/New_York",  # FL (Orlando area)
    "323": "America/Los_Angeles", # CA (LA)
    "325": "America/Chicago",   # TX (Abilene - Central)
    "326": "America/New_York",  # OH (Dayton overlay)
    "330": "America/New_York",  # OH (Youngstown/Akron)
    "331": "America/Chicago",   # IL (western suburbs - Central)
    "332": "America/New_York",  # NY (Manhattan overlay)
    "334": "America/Chicago",   # AL (Montgomery - Central)
    "336": "America/New_York",  # NC (Greensboro)
    "337": "America/Chicago",   # LA (Lafayette - Central)
    "339": "America/New_York",  # MA (Boston overlay)
    "340": "America/New_York",  # US Virgin Islands
    "341": "America/Los_Angeles", # CA (Oakland overlay)
    "346": "America/Chicago",   # TX (Houston overlay - Central)
    "347": "America/New_York",  # NY (NYC boroughs)
    "351": "America/New_York",  # MA (northern)
    "352": "America/New_York",  # FL (Gainesville)
    "360": "America/Los_Angeles", # WA (western WA - Pacific)
    "361": "America/Chicago",   # TX (Corpus Christi - Central)
    "364": "America/Chicago",   # KY (western - Central)
    "380": "America/New_York",  # OH (Columbus overlay)
    "385": "America/Denver",    # UT (Salt Lake overlay)
    "386": "America/New_York",  # FL (Daytona Beach)
    "401": "America/New_York",  # RI
    "402": "America/Chicago",   # NE (Omaha - Central)
    "404": "America/New_York",  # GA (Atlanta)
    "405": "America/Chicago",   # OK (Oklahoma City - Central)
    "406": "America/Denver",    # MT
    "407": "America/New_York",  # FL (Orlando)
    "408": "America/Los_Angeles", # CA (San Jose)
    "409": "America/Chicago",   # TX (Beaumont - Central)
    "410": "America/New_York",  # MD (Baltimore)
    "412": "America/New_York",  # PA (Pittsburgh)
    "413": "America/New_York",  # MA (Springfield)
    "414": "America/Chicago",   # WI (Milwaukee - Central)
    "415": "America/Los_Angeles", # CA (San Francisco)
    "417": "America/Chicago",   # MO (Springfield - Central)
    "419": "America/New_York",  # OH (Toledo)
    "423": "America/New_York",  # TN (eastern)
    "424": "America/Los_Angeles", # CA (LA overlay)
    "425": "America/Los_Angeles", # WA (Bellevue/Redmond - Pacific)
    "430": "America/Chicago",   # TX (eastern - Central)
    "432": "America/Chicago",   # TX (Midland/Odessa - Central)
    "434": "America/New_York",  # VA (Charlottesville)
    "435": "America/Denver",    # UT
    "440": "America/New_York",  # OH (Cleveland suburbs)
    "442": "America/Los_Angeles", # CA (Coachella Valley)
    "443": "America/New_York",  # MD (Baltimore overlay)
    "445": "America/New_York",  # PA (Philadelphia overlay)
    "447": "America/Chicago",   # IL (central - Central)
    "458": "America/Los_Angeles", # OR (Eugene overlay - Pacific)
    "463": "America/New_York",  # IN (Indianapolis overlay)
    "464": "America/Chicago",   # IL (Chicago south - Central)
    "469": "America/Chicago",   # TX (Dallas - Central)
    "470": "America/New_York",  # GA (Atlanta overlay)
    "475": "America/New_York",  # CT (overlay)
    "478": "America/New_York",  # GA (Macon)
    "479": "America/Chicago",   # AR (Fort Smith - Central)
    "480": "America/Phoenix",   # AZ (Phoenix area - Arizona does not observe DST)
    "484": "America/New_York",  # PA (eastern PA overlay)
    "501": "America/Chicago",   # AR (Little Rock - Central)
    "502": "America/New_York",  # KY (Louisville - Eastern observed)
    "503": "America/Los_Angeles", # OR (Portland - Pacific)
    "504": "America/Chicago",   # LA (New Orleans - Central)
    "505": "America/Denver",    # NM
    "507": "America/Chicago",   # MN (Rochester - Central)
    "508": "America/New_York",  # MA (Worcester)
    "509": "America/Los_Angeles", # WA (eastern WA - Pacific)
    "510": "America/Los_Angeles", # CA (Oakland)
    "512": "America/Chicago",   # TX (Austin - Central)
    "513": "America/New_York",  # OH (Cincinnati)
    "515": "America/Chicago",   # IA (Des Moines - Central)
    "516": "America/New_York",  # NY (Long Island)
    "517": "America/New_York",  # MI (Lansing)
    "518": "America/New_York",  # NY (Albany)
    "520": "America/Phoenix",   # AZ (Tucson - Arizona no DST)
    "530": "America/Los_Angeles", # CA (Redding - Pacific)
    "531": "America/Chicago",   # NE (Omaha overlay - Central)
    "534": "America/Chicago",   # WI (Eau Claire - Central)
    "539": "America/Chicago",   # OK (Tulsa overlay - Central)
    "540": "America/New_York",  # VA (Roanoke)
    "541": "America/Los_Angeles", # OR (Eugene/Medford - Pacific)
    "551": "America/New_York",  # NJ (overlay)
    "559": "America/Los_Angeles", # CA (Fresno - Pacific)
    "561": "America/New_York",  # FL (West Palm Beach)
    "562": "America/Los_Angeles", # CA (Long Beach)
    "563": "America/Chicago",   # IA (Davenport - Central)
    "564": "America/Los_Angeles", # WA (western WA overlay - Pacific)
    "567": "America/New_York",  # OH (Toledo overlay)
    "570": "America/New_York",  # PA (Scranton)
    "571": "America/New_York",  # VA (NoVA - Eastern)
    "573": "America/Chicago",   # MO (Columbia - Central)
    "574": "America/New_York",  # IN (South Bend - Eastern observed)
    "575": "America/Denver",    # NM (overlay)
    "580": "America/Chicago",   # OK (southwestern - Central)
    "585": "America/New_York",  # NY (Rochester)
    "586": "America/New_York",  # MI (Macomb County)
    "601": "America/Chicago",   # MS (Jackson - Central)
    "602": "America/Phoenix",   # AZ (Phoenix - Arizona no DST)
    "603": "America/New_York",  # NH
    "605": "America/Chicago",   # SD (eastern - Central)
    "606": "America/New_York",  # KY (eastern)
    "607": "America/New_York",  # NY (Binghamton)
    "608": "America/Chicago",   # WI (Madison - Central)
    "609": "America/New_York",  # NJ (Trenton)
    "610": "America/New_York",  # PA (Philadelphia suburbs)
    "612": "America/Chicago",   # MN (Minneapolis - Central)
    "614": "America/New_York",  # OH (Columbus)
    "615": "America/Chicago",   # TN (Nashville - Central)
    "616": "America/New_York",  # MI (Grand Rapids)
    "617": "America/New_York",  # MA (Boston)
    "618": "America/Chicago",   # IL (southern - Central)
    "619": "America/Los_Angeles", # CA (San Diego)
    "620": "America/Chicago",   # KS (Dodge City - Central)
    "623": "America/Phoenix",   # AZ (Phoenix west - Arizona no DST)
    "624": "America/Chicago",   # IL (overlay)
    "626": "America/Los_Angeles", # CA (Pasadena)
    "628": "America/Los_Angeles", # CA (San Francisco overlay)
    "629": "America/Chicago",   # TN (Nashville overlay - Central)
    "630": "America/Chicago",   # IL (DuPage County - Central)
    "631": "America/New_York",  # NY (Long Island)
    "636": "America/Chicago",   # MO (St. Louis suburbs - Central)
    "641": "America/Chicago",   # IA (Mason City - Central)
    "646": "America/New_York",  # NY (Manhattan overlay)
    "650": "America/Los_Angeles", # CA (San Mateo)
    "651": "America/Chicago",   # MN (St. Paul - Central)
    "657": "America/Los_Angeles", # CA (Orange County overlay)
    "659": "America/Chicago",   # AL (Birmingham overlay - Central)
    "660": "America/Chicago",   # MO (northwest - Central)
    "661": "America/Los_Angeles", # CA (Bakersfield)
    "662": "America/Chicago",   # MS (northern - Central)
    "667": "America/New_York",  # MD (Baltimore overlay)
    "669": "America/Los_Angeles", # CA (San Jose overlay)
    "671": "America/Guam",      # Guam (US territory)
    "678": "America/New_York",  # GA (Atlanta overlay)
    "681": "America/New_York",  # WV (overlay)
    "682": "America/Chicago",   # TX (Fort Worth overlay - Central)
    "689": "America/New_York",  # FL (Orlando overlay)
    "701": "America/Chicago",   # ND (Central)
    "702": "America/Los_Angeles", # NV (Las Vegas - Pacific)
    "703": "America/New_York",  # VA (NoVA - Eastern)
    "704": "America/New_York",  # NC (Charlotte)
    "706": "America/New_York",  # GA (Augusta)
    "707": "America/Los_Angeles", # CA (Santa Rosa)
    "708": "America/Chicago",   # IL (Chicago south suburbs - Central)
    "712": "America/Chicago",   # IA (Sioux City - Central)
    "713": "America/Chicago",   # TX (Houston - Central)
    "714": "America/Los_Angeles", # CA (Anaheim)
    "715": "America/Chicago",   # WI (northern - Central)
    "716": "America/New_York",  # NY (Buffalo)
    "717": "America/New_York",  # PA (Harrisburg)
    "718": "America/New_York",  # NY (NYC boroughs)
    "719": "America/Denver",    # CO (Colorado Springs)
    "720": "America/Denver",    # CO (Denver overlay)
    "724": "America/New_York",  # PA (Pittsburgh suburbs)
    "725": "America/Los_Angeles", # NV (Las Vegas overlay - Pacific)
    "726": "America/Chicago",   # TX (San Antonio overlay - Central)
    "727": "America/New_York",  # FL (St. Petersburg)
    "730": "America/Chicago",   # IL (overlay)
    "731": "America/Chicago",   # TN (western - Central)
    "732": "America/New_York",  # NJ (central)
    "734": "America/New_York",  # MI (Ann Arbor)
    "737": "America/Chicago",   # TX (Austin overlay - Central)
    "740": "America/New_York",  # OH (southeastern)
    "743": "America/New_York",  # NC (Greensboro overlay)
    "747": "America/Los_Angeles", # CA (San Fernando Valley overlay)
    "754": "America/New_York",  # FL (Fort Lauderdale overlay)
    "757": "America/New_York",  # VA (Norfolk/Virginia Beach)
    "760": "America/Los_Angeles", # CA (Palm Springs/Riverside)
    "762": "America/New_York",  # GA (Augusta overlay)
    "763": "America/Chicago",   # MN (Minneapolis suburbs - Central)
    "765": "America/New_York",  # IN (Lafayette - Eastern observed)
    "769": "America/Chicago",   # MS (Jackson overlay - Central)
    "770": "America/New_York",  # GA (Atlanta suburbs)
    "771": "America/New_York",  # MD (overlay)
    "772": "America/New_York",  # FL (Fort Pierce)
    "773": "America/Chicago",   # IL (Chicago - Central)
    "774": "America/New_York",  # MA (Worcester overlay)
    "775": "America/Los_Angeles", # NV (Reno - Pacific)
    "779": "America/Chicago",   # IL (Rockford overlay - Central)
    "781": "America/New_York",  # MA (Boston suburbs)
    "785": "America/Chicago",   # KS (Topeka - Central)
    "786": "America/New_York",  # FL (Miami overlay)
    "787": "America/Puerto_Rico", # Puerto Rico
    "801": "America/Denver",    # UT (Salt Lake City)
    "802": "America/New_York",  # VT
    "803": "America/New_York",  # SC (Columbia)
    "804": "America/New_York",  # VA (Richmond)
    "805": "America/Los_Angeles", # CA (Ventura/Santa Barbara)
    "806": "America/Chicago",   # TX (Amarillo - Central)
    "808": "Pacific/Honolulu",  # HI
    "810": "America/New_York",  # MI (Flint)
    "812": "America/New_York",  # IN (Evansville - Eastern observed)
    "813": "America/New_York",  # FL (Tampa)
    "814": "America/New_York",  # PA (Erie)
    "815": "America/Chicago",   # IL (Rockford - Central)
    "816": "America/Chicago",   # MO (Kansas City - Central)
    "817": "America/Chicago",   # TX (Fort Worth - Central)
    "818": "America/Los_Angeles", # CA (San Fernando Valley)
    "820": "America/Los_Angeles", # CA (Santa Barbara overlay)
    "825": "America/Denver",    # AB Canada - treat as Mountain if called
    "828": "America/New_York",  # NC (Asheville)
    "830": "America/Chicago",   # TX (San Antonio area - Central)
    "831": "America/Los_Angeles", # CA (Monterey/Santa Cruz)
    "832": "America/Chicago",   # TX (Houston overlay - Central)
    "838": "America/New_York",  # NY (Albany overlay)
    "839": "America/New_York",  # SC (Myrtle Beach overlay)
    "840": "America/Los_Angeles", # CA (Riverside overlay)
    "843": "America/New_York",  # SC (Myrtle Beach/Charleston)
    "845": "America/New_York",  # NY (Hudson Valley)
    "847": "America/Chicago",   # IL (northern suburbs - Central)
    "848": "America/New_York",  # NJ (central overlay)
    "850": "America/Chicago",   # FL (Panhandle - Central)
    "854": "America/New_York",  # SC (Charleston overlay)
    "856": "America/New_York",  # NJ (southern)
    "857": "America/New_York",  # MA (Boston overlay)
    "858": "America/Los_Angeles", # CA (San Diego north)
    "859": "America/New_York",  # KY (Lexington - Eastern observed)
    "860": "America/New_York",  # CT (Hartford)
    "862": "America/New_York",  # NJ (Newark overlay)
    "863": "America/New_York",  # FL (Lakeland)
    "864": "America/New_York",  # SC (Greenville)
    "865": "America/New_York",  # TN (Knoxville)
    "870": "America/Chicago",   # AR (eastern - Central)
    "872": "America/Chicago",   # IL (Chicago overlay - Central)
    "878": "America/New_York",  # PA (Pittsburgh overlay)
    "901": "America/Chicago",   # TN (Memphis - Central)
    "903": "America/Chicago",   # TX (Tyler/Longview - Central)
    "904": "America/New_York",  # FL (Jacksonville)
    "906": "America/New_York",  # MI (Upper Peninsula)
    "907": "America/Anchorage", # AK
    "908": "America/New_York",  # NJ (central)
    "909": "America/Los_Angeles", # CA (Inland Empire)
    "910": "America/New_York",  # NC (Wilmington/Fayetteville)
    "912": "America/New_York",  # GA (Savannah)
    "913": "America/Chicago",   # KS (Kansas City area - Central)
    "914": "America/New_York",  # NY (Westchester)
    "915": "America/Denver",    # TX (El Paso - Mountain)
    "916": "America/Los_Angeles", # CA (Sacramento)
    "917": "America/New_York",  # NY (NYC overlay)
    "918": "America/Chicago",   # OK (Tulsa - Central)
    "919": "America/New_York",  # NC (Raleigh)
    "920": "America/Chicago",   # WI (Green Bay - Central)
    "925": "America/Los_Angeles", # CA (Walnut Creek/Concord)
    "928": "America/Phoenix",   # AZ (Flagstaff/Yuma - Arizona no DST)
    "929": "America/New_York",  # NY (NYC overlay)
    "930": "America/New_York",  # IN (Bloomington overlay)
    "931": "America/Chicago",   # TN (Clarksville - Central)
    "934": "America/New_York",  # NY (Long Island overlay)
    "936": "America/Chicago",   # TX (Lufkin - Central)
    "937": "America/New_York",  # OH (Dayton)
    "938": "America/Chicago",   # AL (Huntsville overlay - Central)
    "939": "America/Puerto_Rico", # Puerto Rico overlay
    "940": "America/Chicago",   # TX (Wichita Falls - Central)
    "941": "America/New_York",  # FL (Sarasota)
    "945": "America/Chicago",   # TX (Dallas overlay - Central)
    "947": "America/New_York",  # MI (Oakland County overlay)
    "948": "America/New_York",  # VA (NoVA overlay)
    "949": "America/Los_Angeles", # CA (Irvine/Newport Beach)
    "951": "America/Los_Angeles", # CA (Riverside)
    "952": "America/Chicago",   # MN (Minneapolis suburbs - Central)
    "954": "America/New_York",  # FL (Fort Lauderdale)
    "956": "America/Chicago",   # TX (Laredo/McAllen - Central)
    "959": "America/New_York",  # CT (overlay)
    "970": "America/Denver",    # CO (western)
    "971": "America/Los_Angeles", # OR (Portland overlay - Pacific)
    "972": "America/Chicago",   # TX (Dallas - Central)
    "973": "America/New_York",  # NJ (Newark)
    "978": "America/New_York",  # MA (northern)
    "979": "America/Chicago",   # TX (College Station - Central)
    "980": "America/New_York",  # NC (Charlotte overlay)
    "984": "America/New_York",  # NC (Raleigh overlay)
    "985": "America/Chicago",   # LA (Slidell - Central)
    "986": "America/Denver",    # ID (Boise overlay)
    "989": "America/New_York",  # MI (Saginaw)
}


def get_timezone_for_npa(e164_destination: str) -> Optional[str]:
    """Return the IANA timezone for a US E.164 destination, or None if unknown.

    Extracts the 3-digit NPA (area code) from a US E.164 number (+1NPAXXXXXXX)
    and looks it up in the NPA_TIMEZONES dict.

    Args:
        e164_destination: E.164 phone number string, e.g. "+12125551234".
                          Must start with "+1" followed by 10 digits.

    Returns:
        IANA timezone string (e.g. "America/New_York") if NPA is known,
        None if NPA is not found (fail-closed: caller must deny the call per D-13).
    """
    # E.164 US numbers: +1 followed by 10 digits (NPA + NXX + XXXX)
    if not e164_destination or not e164_destination.startswith("+1"):
        return None
    digits = e164_destination[2:]  # Strip the "+1"
    if len(digits) < 3:
        return None
    npa = digits[:3]
    return NPA_TIMEZONES.get(npa)
